<?php
/**
 * Dependency Installer
 *
 * Auto-installs mPDF if vendor directory is missing
 */

if (!defined('ABSPATH')) {
    exit;
}

class Custom_Cert_Dependency_Installer {

    private static $instance = null;

    public static function get_instance() {
        if (null === self::$instance) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Check if dependencies are installed
     *
     * @return bool
     */
    public static function dependencies_installed() {
        $vendor_autoload = CUSTOM_CERT_PLUGIN_DIR . 'vendor/autoload.php';
        return file_exists($vendor_autoload) && class_exists('\\Mpdf\\Mpdf');
    }

    /**
     * Install dependencies
     *
     * @return bool|WP_Error
     */
    public static function install_dependencies() {
        // Check if we can write to the plugin directory
        if (!is_writable(CUSTOM_CERT_PLUGIN_DIR)) {
            return new WP_Error(
                'directory_not_writable',
                __('El directorio del plugin no tiene permisos de escritura. Por favor, contacta con tu administrador del servidor.', 'custom-certificates')
            );
        }

        // Download mPDF standalone
        return self::download_mpdf_standalone();
    }

    /**
     * Download and install mPDF standalone version
     *
     * @return bool|WP_Error
     */
    private static function download_mpdf_standalone() {
        require_once ABSPATH . 'wp-admin/includes/file.php';

        $mpdf_version = '8.1.4';
        $download_url = "https://github.com/mpdf/mpdf/releases/download/v{$mpdf_version}/mpdf.zip";

        // Create vendor directory
        $vendor_dir = CUSTOM_CERT_PLUGIN_DIR . 'vendor';
        if (!file_exists($vendor_dir)) {
            wp_mkdir_p($vendor_dir);
        }

        // Download file
        $temp_file = download_url($download_url);

        if (is_wp_error($temp_file)) {
            return new WP_Error(
                'download_failed',
                sprintf(
                    __('No se pudo descargar mPDF: %s', 'custom-certificates'),
                    $temp_file->get_error_message()
                )
            );
        }

        // Unzip
        $unzip_result = unzip_file($temp_file, $vendor_dir);

        // Clean up
        @unlink($temp_file);

        if (is_wp_error($unzip_result)) {
            return new WP_Error(
                'unzip_failed',
                sprintf(
                    __('No se pudo descomprimir mPDF: %s', 'custom-certificates'),
                    $unzip_result->get_error_message()
                )
            );
        }

        // Create autoload.php
        self::create_autoload();

        return true;
    }

    /**
     * Create a simple autoload.php file for mPDF
     */
    private static function create_autoload() {
        $autoload_content = <<<'PHP'
<?php
/**
 * Autoloader for mPDF
 * Auto-generated by Custom Certificates plugin
 */

spl_autoload_register(function ($class) {
    // Only load mPDF classes
    if (strpos($class, 'Mpdf\\') !== 0) {
        return;
    }

    // Convert namespace to file path
    $file = __DIR__ . '/mpdf/' . str_replace('\\', '/', substr($class, 5)) . '.php';

    if (file_exists($file)) {
        require_once $file;
    }
});
PHP;

        $autoload_file = CUSTOM_CERT_PLUGIN_DIR . 'vendor/autoload.php';
        file_put_contents($autoload_file, $autoload_content);
    }

    /**
     * Show admin notice if dependencies are missing
     */
    public static function admin_notice_missing_dependencies() {
        ?>
        <div class="notice notice-warning is-dismissible">
            <p>
                <strong><?php _e('Custom Certificates:', 'custom-certificates'); ?></strong>
                <?php _e('El plugin necesita instalar dependencias para funcionar correctamente.', 'custom-certificates'); ?>
            </p>
            <p>
                <a href="<?php echo admin_url('admin.php?page=cert-install-dependencies'); ?>" class="button button-primary">
                    <?php _e('Instalar Dependencias Automáticamente', 'custom-certificates'); ?>
                </a>
                <a href="<?php echo admin_url('edit.php?post_type=bb_cert_template&page=cert-settings#manual-install'); ?>" class="button">
                    <?php _e('Instrucciones de Instalación Manual', 'custom-certificates'); ?>
                </a>
            </p>
        </div>
        <?php
    }

    /**
     * Handle dependency installation page
     */
    public static function dependency_installation_page() {
        if (!current_user_can('manage_options')) {
            wp_die(__('No tienes permisos para realizar esta acción.', 'custom-certificates'));
        }

        ?>
        <div class="wrap">
            <h1><?php _e('Instalación de Dependencias - Custom Certificates', 'custom-certificates'); ?></h1>

            <?php
            if (isset($_POST['install_dependencies']) && check_admin_referer('install_cert_dependencies')) {
                echo '<div class="notice notice-info"><p>' . __('Instalando dependencias, por favor espera...', 'custom-certificates') . '</p></div>';

                $result = self::install_dependencies();

                if (is_wp_error($result)) {
                    echo '<div class="notice notice-error"><p><strong>' . __('Error:', 'custom-certificates') . '</strong> ' . esc_html($result->get_error_message()) . '</p></div>';
                } else {
                    echo '<div class="notice notice-success"><p>' . __('¡Dependencias instaladas correctamente!', 'custom-certificates') . '</p></div>';
                    echo '<script>setTimeout(function(){ window.location.href = "' . admin_url('edit.php?post_type=bb_cert_template') . '"; }, 2000);</script>';
                }
            }
            ?>

            <div class="card">
                <h2><?php _e('Instalación Automática', 'custom-certificates'); ?></h2>
                <p><?php _e('Este plugin requiere la librería mPDF para generar certificados en PDF.', 'custom-certificates'); ?></p>
                <p><?php _e('Haz clic en el botón de abajo para instalarla automáticamente (requiere conexión a internet).', 'custom-certificates'); ?></p>

                <form method="post">
                    <?php wp_nonce_field('install_cert_dependencies'); ?>
                    <p>
                        <button type="submit" name="install_dependencies" class="button button-primary button-hero">
                            <?php _e('Instalar Dependencias Ahora', 'custom-certificates'); ?>
                        </button>
                    </p>
                </form>
            </div>

            <div class="card" style="margin-top: 20px;">
                <h2 id="manual-install"><?php _e('Instalación Manual (Alternativa)', 'custom-certificates'); ?></h2>
                <p><?php _e('Si la instalación automática no funciona, puedes instalar las dependencias manualmente:', 'custom-certificates'); ?></p>

                <ol>
                    <li>
                        <strong><?php _e('Si tienes acceso SSH:', 'custom-certificates'); ?></strong>
                        <pre style="background: #f5f5f5; padding: 10px; border: 1px solid #ddd;">cd <?php echo CUSTOM_CERT_PLUGIN_DIR; ?>
composer install --no-dev</pre>
                    </li>
                    <li>
                        <strong><?php _e('Si NO tienes acceso SSH:', 'custom-certificates'); ?></strong>
                        <ol>
                            <li><?php _e('Descarga el plugin completo con dependencias desde:', 'custom-certificates'); ?> <a href="#">GitHub Releases</a></li>
                            <li><?php _e('Descomprímelo y súbelo completo al servidor', 'custom-certificates'); ?></li>
                        </ol>
                    </li>
                </ol>
            </div>
        </div>
        <?php
    }
}
